# Generated by Django 4.2.27 on 2025-12-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
