# Generated by Django 4.2.27 on 2025-12-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_account_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image_url', models.CharField(max_length=500)),
                ('product_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
