# Generated by Django 4.2.27 on 2025-12-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_total',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
