# Generated by Django 4.2.27 on 2025-12-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_cart_item_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
