# Generated by Django 4.2.27 on 2026-01-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('pending_capture', 'Ожидает подтверждения'), ('completed', 'Оплачен'), ('failed', 'Неудачный'), ('canceled', 'Отменен')], default='pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('items', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
