# Generated by Django 4.2.27 on 2026-01-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
